### ISSUE TITLE
Can it support the same scrolling style as PhotoShop?

### ISSUE THREAD

**Issue by Charltsing** [d2phap/DXControl#3]
Add horizontal and vertical scrollbars,

Mouse Wheel         --> move up and down
Ctrl+Mouse Wheel --> move left and right
Alt+Mouse Wheel           --> Zoom

so i can make it easier to view image details

**Comment by d2phap** [comment]
This is a low-level control for drawing with Direct2D and GDI+. You need to implement all the functions by yourself.

**Comment by Charltsing** [comment]
> This is a low-level control for drawing with Direct2D and GDI+. You need to implement all the functions by yourself.

how to show horizontal and vertical scrollbars ?
