### ISSUE TITLE
How to get pixel color?

### ISSUE THREAD

**Issue by Charltsing** [d2phap/DXControl#4]
I want to obtain the current pixel color in the mouse event on the canvas,
How to get pixel color in it? (not from bitmap)

**Comment by d2phap** [comment]
You need to copy bitmap data from GPU to CPU, then use [`ID2D1Bitmap1.Map()`](https://learn.microsoft.com/en-us/windows/win32/api/d2d1_1/nf-d2d1_1-id2d1bitmap1-map) method.

See https://github.com/d2phap/ImageGlass/blob/e2045cb557300df4260e3374554efa0597bee561/Source/Components/ImageGlass.Base/BHelper/Extensions/ID2D1Bitmap1Extensions.cs#L33-L76

**Comment by Charltsing** [comment]
Thank you, I will try

**Comment by Charltsing** [comment]
how to use copypixels in WIC ?

https://learn.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicbitmapsource-copypixels

**Comment by d2phap** [comment]
This library is just provide Direct2D API for WinForms, to start building something with this, you need to learn Direct2D.

> how to use copypixels in WIC ? perhaps this can be faster?
This question is not related to this library. You need to try and check by yourself.
