### ISSUE TITLE
How to save the content of the demo window as an image?

### ISSUE THREAD

**Issue by Charltsing** [d2phap/DXControl#6]
![捕获](https://github.com/d2phap/DXControl/assets/19963715/b19305a2-f668-4d0f-9745-467dbb00a310)

How to save the content of the demo window as an image?
Do you plan to add the feature of saving window content in the demo

**Comment by d2phap** [comment]
I don't have a solution right now, but I found this doc, you can try:
https://learn.microsoft.com/en-us/windows/win32/direct2d/save-direct2d-content-to-an-image-file#what-you-need-to-know

**Comment by Charltsing** [comment]
I use  CopyFromRenderTarget to save window content
[DXControl-save.zip](https://github.com/d2phap/DXControl/files/15430680/DXControl-save.zip)

![shot](https://github.com/d2phap/DXControl/assets/19963715/21ce89b4-ff46-43d8-8d84-643f1d5ba031)
